### ISSUE TITLE
~/.spotify-ripper is not a dir on OSX install

### ISSUE THREAD

**Issue by MichaelRobertBell** [jrnewell/spotify-ripper#142]
Hello boys,

For some reason on install the ~/.spotify-ripper dir is not a dir. 
Installed using the instructions listed on the site using ZSH.

**Comment by jrnewell** [comment]
what do you mean, like it is just a regular file?  Just delete whatever is there and do ``mkdir ~/.spotify-ripper`` and copy your key into there and you should be good to go....

**Comment by MichaelRobertBell** [comment]
Yeah! Sorry I was just waking up. For some reason a file was created named .spotify-ripper. I since deleted it and everything is working great!

**Comment by 14granville** [comment]
I had a similar issue when installing spotify-ripper for my brother. After completing the installation, I couldn't find the .spotify-ripper directory anywhere. I spent like half an hour looking for it as you need it to put the spotify appkey file in it. So, as stated above, I just created it out of the blue, I put it in ~/, I put the spotify.appkey in it and everything works fine since then.

**Comment by jrnewell** [comment]
Well, it doesn't automatically create the ~/.spotify-ripper directory during the install because you have the option to use a different directory for your settings directory (it will create your settings directory on the first run if it doesn't exist).  I guess I could add more instruction in the README to be clear that you should create the directory.
