### ISSUE TITLE
What is the best way of saving to 320 kbps MP3 without losing quality?

### ISSUE THREAD

**Issue by mR12KL** [jrnewell/spotify-ripper#149]
I read the other topic on transcodes, but I wasn't able to come out with a clear answer.

Do you download in ogg v9 and convert to 320 kbps MP3?
Do you download in mp3 320 and keep it that way?
Do you download in FLAC and convert to MP3 320?

Or a different method? All I want to do is retain the quality as much as possible with the output being 320 kbps MP3. Thanks!

**Comment by jrnewell** [comment]
I am not an audiophile, so maybe another user can give their input, but from what I understand, Spotify streams in at 320 kps in OGG compressed format.  Spotify-ripper gets the uncompressed ogg stream and redirects the stream to another compressed format of your choosing.  It is not clear if transcoding to a non-OGG compression is worse than compressing back to OGG or not.  Hope that helps...

**Comment by mR12KL** [comment]
Thanks! I'll leave this open for a little while to see if any other user wants to give input.

**Comment by promasterx** [comment]
I am having similar problem with segmentation in the middle of ripping. In order to fix it first I change audio format to -flac, then I cancel the process, remove the -flac option then it start it again. When it doesn't help i try with other formats.  

It is a bit annoying to check every half an hour whether ripping is going well

Would appreciate tips to fix it forever )

`Spotify Ripper - v2.8.3`
`Encoding output:  MP3, VBR 0`
`  Spotify bitrate:  320 kbps`
`  Unicode support:  Yes`
`  Output directory: /Users/serveradmin/Desktop/Ripped Spotify`
`  Settings directory: /Users/serveradmin/.spotify-ripper`
`  Format String:  {album_artist}/{album}/{artist} - {track_name}.{ext}`
`  Overwrite files:  No`
`Logging in...`
`Logged in as xxxxx`
`Loading playlist...`
`Total Download Size: 1.69 GB`
`Loading playlist...`
`Loading track...`
`Skipping spotify:track:0rnWD40M2swoFgneMeehsZ
/Users/serveradmin/Desktop/Ripped Spotify/Thirty Seconds To Mars/Hurricane 2.0/Thirty Seconds To Mars - Hurricane 2.0.mp3`
`Removing successfully ripped tracks from playlist Thirty Seconds To Mars - Hurricane 2.0...`
`Loading playlist...`
`Removing successfully ripped tracks from playlist 30.02 - Primerom...`
`Segmentation fault: 11``
