### ISSUE TITLE
Can't save song in 320kbps CBR

### ISSUE THREAD

**Issue by Frigerald** [jrnewell/spotify-ripper#157]
So i'm guessing the quality setting is not working or i am interpreting command list wrong. Every time i try to make mp3 file it chooses VBR settings. Example:
Let's say i'm searching for a song and spotify-ripper successfully finds it. 
It shows that 'Track Download Size: 8.01 MB'.
I tried 2 approaches (with-Q and -q):
spotify-ripper -u user-p password -Q 320  -o spotify:track:urlofttrack
  Encoding output:	MP3, VBR 0
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
spotify-ripper -u user-p password -q VBR -o spotify:track:urlofttrack
  Encoding output:	MP3, VBR VBR
  Spotify bitrate:	320 kbps
  Unicode support:	Yes
Both cases outputs the same mp3 file with VBR quality (224kbps, 6,9MB). Shouldn't the command -Q 320 output 320kbps CBR file?

**Comment by jrnewell** [comment]
Try using the arguments ``--cbr --bitrate 320`` for 320 kpbs CBR encoding

**Comment by Frigerald** [comment]
Interesting, that really did the trick. Although I still don't understand why would you include 2 options for quality if both of them creates the same output. Also, I checked if the constant bitrate changes something in the spectrum analyser. As far as I understand, when i use CBR, frequencies above 20kHz are discarded.
File spectrum using VBR encoding:
![VBR](http://s23.postimg.org/aykw5c363/image.png)
File spectrum using CBR encoding:
![CBR](http://s30.postimg.org/4bb1bv8tt/image.png)

**Comment by jrnewell** [comment]
Yeah it is kind of a hodgepodge of options because there each encoder tends to have a different set of options and there are some overlap between them plus there is are options to control Spotify.

The difference between ``-Q`` and ``-q`` is that one controls the bitrate that Spotify streams at and the other the quality of the encoder in "vbr" mode using an integer.  I am not sure why the high freq are cutoff in CBR encoding - this actually is done in the lame encoder.  Might want to ask their team?

**Comment by portableko** [comment]
Files encoded in VBR is a bit louder than CBR. I tested it on my iPod Nano.
