### ISSUE TITLE
ASCII, directory, remove-from-playlist

### ISSUE THREAD

**Issue by WebDesZ** [jrnewell/spotify-ripper#17]
1)
There seems to be a problem with the "directory" in the config.ini.
It does not use the path I wrote in the file.
(directory = /mnt/****/*******/music/)

2) 
I set "remove_from_playlist = True" and it seems as this function is broken as nothing happens. (Also when I set it as an command line argument. 

3)
Would be awesome if you add the genre to the ID3-Tags
I know that spotify does not provide this api for each song but it provides it for each album and artist.
(Read: https://github.com/spotify/web-api/issues/31)

4)
I have to use the "-a" flag as I get a lot of errors if I don't. But could you just convert the filenames to ascii and not the ID3-Tags? 

Thank you so much :)

**Comment by jrnewell** [comment]
1.)  This is a bug.  Fixed in e4fa643 / version ``1.1.4``

2.)  I just tried this feature (using the command line) and it seemed to work for me.  Note that it doesn't remove the tracks from the playlist until the very end (ripped everything and about to logout).  Also you need to enter a URI of a playlist that is owned by the user that you logged in as.

3.)  OK - I will look into this.  It doesn't look like it is available through libspotify and would have to use the web API that you linked to.  On a side note, [beets](http://beets.radbox.org/) does a very good job for getting advance metadata automatically.

4.) I added an option ``-A | --ascii-path-only`` to e6d9157 / version ``1.1.4`` that will not ASCIIfy the ID3 tags, but only the path.

**Comment by jrnewell** [comment]
3.) I added this feature in abb8b89 / version ``1.2.0``.  When I was playing around with it, it looks like Spotify doesn't have genre data populated yet (mostly blank for most albums).
