### ISSUE TITLE
Time estimates vary considerably

### ISSUE THREAD

**Issue by dylanjboyd** [jrnewell/spotify-ripper#35]
Time estimates for individual tracks and for total downloads can vary considerably. An example of this is a 51-hour download's estimated total completion time ranging from *1 day and 7 hours* to *1 day and 12 hours*.

Would it be possible to display the estimated remaining download time based on **download rate samples** from a fixed time period, say one minute? This would cause less instability in displayed values.

**Comment by jrnewell** [comment]
yeah it is not quite straight forward on the best approach because download speed can vary quite considerably within a single file download due to various factors (ISP throttling, congestion, wifi issues etc).  It does use download rate samples but at ~2 sec intervals.  I did some research and it appears that using an exponential moving average of download rates is the best approach.  I will try that to see if that makes a difference.

**Comment by jrnewell** [comment]
Added the EMA smoothing in version ``1.3.2``.  Can you check if this solves your issue?

**Comment by dylanjboyd** [comment]
Much better, thank you. The estimates look stable for the current track and for overall download estimates.
