### ISSUE TITLE
Suggestion: Rename flag

### ISSUE THREAD

**Issue by TobyMellor** [jrnewell/spotify-ripper#38]
Hi,
Could you put in a --name -n flag that saves the song file as that name?
Example: spotify-ripper --name myAwesomeSong.mp3 mysongid
Thanks!

**Comment by dylanjboyd** [comment]
Would this work given the fact that the Ripper can also work on artists, albums, and playlists?

**Comment by TobyMellor** [comment]
I only need it to work if the -flat flag is given

**Comment by dylanjboyd** [comment]
If the flat flag is given, the ripper can still rip multiple songs given an ID of the aforementioned types (artist, album, or playlist). If an artist is provided, and you specify `-flat`, it will rip all songs from that artist into the same directory. In addition, you would like to specify a name for the output files of the ripper, but since this will likely be multiple files, it will attempt to name all of those files with the same name (that you specified), so I struggle to see how this would work.

**Comment by TobyMellor** [comment]
Good point... I'll try find another way around my issue

**Comment by dylanjboyd** [comment]
Was the scenario you mentioned only thought of in the context of a song URI to be ripped, or did you also want to rip "collection" URIs using the same filename? Is there any particular reason as to why you wish to specify the filename? Knowing this could make it easier to find a solution that would work with the Ripper.

**Comment by TobyMellor** [comment]
I thought my issue would be fixed by specifying a file output name, but I've just added checks/ renamed it afterwards. All is good.

**Comment by dylanjboyd** [comment]
Glad to hear it. If you've found a way around your issue, please close it.
