### ISSUE TITLE
Downloading paylists should not need user interaction "Pick track(s) ..."

### ISSUE THREAD

**Issue by Anachrostichon** [jrnewell/spotify-ripper#96]
Whenever I try download an entire playlist the following happens:
Searchuing for query: -
Results
Pick track(s) (ex 1-3,5):

I will usually enter 1-99 and the entire playlist is than downloaded. But it prevents using spotify-ripper from beeing usable from shell scripts.
Did I miss some commandline option? Is this inteded or a bug?

**Comment by jrnewell** [comment]
Is there a reason you are using a query search instead of a URI?  If you post your command line args I can help you debug what the issue is.

The best way to download a Spotify playlist is to use the Spotify URI.  You can get it form the Spotify App by right-clicking on a playlist and "Copy Spotify URI".  If you are scripting, take a look into Spotify's Web API to get the URI automatically.

**Comment by lambdamusic** [comment]
Thanks - I was having the same issue and then realized I wasn't using the playlist URI!
